// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOa92wkGndniNYUsvA28sHYh2ZujXPSxk',
    appId: '1:487668312091:web:17c8deb4625976ffc270be',
    messagingSenderId: '487668312091',
    projectId: 'my-workout-app-9deb3',
    authDomain: 'my-workout-app-9deb3.firebaseapp.com',
    storageBucket: 'my-workout-app-9deb3.appspot.com',
    measurementId: 'G-3PV522W704',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT0rwhOEdlKxwXTSijpitDEiSqWzNphDY',
    appId: '1:487668312091:android:55224bafc7e36791c270be',
    messagingSenderId: '487668312091',
    projectId: 'my-workout-app-9deb3',
    storageBucket: 'my-workout-app-9deb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmZssB3MjIAtcgew808khDbygeYJf6ioQ',
    appId: '1:487668312091:ios:1cef7f5e98e6e536c270be',
    messagingSenderId: '487668312091',
    projectId: 'my-workout-app-9deb3',
    storageBucket: 'my-workout-app-9deb3.appspot.com',
    iosClientId: '487668312091-5o8bteel7v1bgo6cv32j11tud9un06jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWorkoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmZssB3MjIAtcgew808khDbygeYJf6ioQ',
    appId: '1:487668312091:ios:1cef7f5e98e6e536c270be',
    messagingSenderId: '487668312091',
    projectId: 'my-workout-app-9deb3',
    storageBucket: 'my-workout-app-9deb3.appspot.com',
    iosClientId: '487668312091-5o8bteel7v1bgo6cv32j11tud9un06jc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWorkoutApp',
  );
}
